name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Change this to your default branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        app: [admin, client]

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14' # Adjust node version as necessary

    - name: Install dependencies
      run: cd ${{ matrix.app }} && npm install

    - name: Build the project
      run: cd ${{ matrix.app }} && npm run build

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ${{ matrix.app }}/dist
        destination_dir: ${{ matrix.app }}
